//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var DeployRuns = newDeployRunsTable("public", "deploy_runs", "")

type deployRunsTable struct {
	postgres.Table

	// Columns
	ID         postgres.ColumnInteger
	DeployID   postgres.ColumnInteger
	Site       postgres.ColumnString
	PipelineID postgres.ColumnInteger
	WebURL     postgres.ColumnString
	Status     postgres.ColumnString
	Error      postgres.ColumnString
	UpdatedAt  postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type DeployRunsTable struct {
	deployRunsTable

	EXCLUDED deployRunsTable
}

// AS creates new DeployRunsTable with assigned alias
func (a DeployRunsTable) AS(alias string) *DeployRunsTable {
	return newDeployRunsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new DeployRunsTable with assigned schema name
func (a DeployRunsTable) FromSchema(schemaName string) *DeployRunsTable {
	return newDeployRunsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new DeployRunsTable with assigned table prefix
func (a DeployRunsTable) WithPrefix(prefix string) *DeployRunsTable {
	return newDeployRunsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new DeployRunsTable with assigned table suffix
func (a DeployRunsTable) WithSuffix(suffix string) *DeployRunsTable {
	return newDeployRunsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newDeployRunsTable(schemaName, tableName, alias string) *DeployRunsTable {
	return &DeployRunsTable{
		deployRunsTable: newDeployRunsTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newDeployRunsTableImpl("", "excluded", ""),
	}
}

func newDeployRunsTableImpl(schemaName, tableName, alias string) deployRunsTable {
	var (
		IDColumn         = postgres.IntegerColumn("id")
		DeployIDColumn   = postgres.IntegerColumn("deploy_id")
		SiteColumn       = postgres.StringColumn("site")
		PipelineIDColumn = postgres.IntegerColumn("pipeline_id")
		WebURLColumn     = postgres.StringColumn("web_url")
		StatusColumn     = postgres.StringColumn("status")
		ErrorColumn      = postgres.StringColumn("error")
		UpdatedAtColumn  = postgres.TimestampzColumn("updated_at")
		allColumns       = postgres.ColumnList{IDColumn, DeployIDColumn, SiteColumn, PipelineIDColumn, WebURLColumn, StatusColumn, ErrorColumn, UpdatedAtColumn}
		mutableColumns   = postgres.ColumnList{DeployIDColumn, SiteColumn, PipelineIDColumn, WebURLColumn, StatusColumn, ErrorColumn, UpdatedAtColumn}
		defaultColumns   = postgres.ColumnList{IDColumn, WebURLColumn, ErrorColumn, UpdatedAtColumn}
	)

	return deployRunsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		DeployID:   DeployIDColumn,
		Site:       SiteColumn,
		PipelineID: PipelineIDColumn,
		WebURL:     WebURLColumn,
		Status:     StatusColumn,
		Error:      ErrorColumn,
		UpdatedAt:  UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
