//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Services = newServicesTable("public", "services", "")

type servicesTable struct {
	postgres.Table

	// Columns
	Name    postgres.ColumnString
	Postfix postgres.ColumnString
	Kind    postgres.ColumnString
	Sites   postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ServicesTable struct {
	servicesTable

	EXCLUDED servicesTable
}

// AS creates new ServicesTable with assigned alias
func (a ServicesTable) AS(alias string) *ServicesTable {
	return newServicesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ServicesTable with assigned schema name
func (a ServicesTable) FromSchema(schemaName string) *ServicesTable {
	return newServicesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ServicesTable with assigned table prefix
func (a ServicesTable) WithPrefix(prefix string) *ServicesTable {
	return newServicesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ServicesTable with assigned table suffix
func (a ServicesTable) WithSuffix(suffix string) *ServicesTable {
	return newServicesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newServicesTable(schemaName, tableName, alias string) *ServicesTable {
	return &ServicesTable{
		servicesTable: newServicesTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newServicesTableImpl("", "excluded", ""),
	}
}

func newServicesTableImpl(schemaName, tableName, alias string) servicesTable {
	var (
		NameColumn     = postgres.StringColumn("name")
		PostfixColumn  = postgres.StringColumn("postfix")
		KindColumn     = postgres.StringColumn("kind")
		SitesColumn    = postgres.StringColumn("sites")
		allColumns     = postgres.ColumnList{NameColumn, PostfixColumn, KindColumn, SitesColumn}
		mutableColumns = postgres.ColumnList{KindColumn, SitesColumn}
		defaultColumns = postgres.ColumnList{PostfixColumn, SitesColumn}
	)

	return servicesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Name:    NameColumn,
		Postfix: PostfixColumn,
		Kind:    KindColumn,
		Sites:   SitesColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
