//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var SiteVersions = newSiteVersionsTable("public", "site_versions", "")

type siteVersionsTable struct {
	postgres.Table

	// Columns
	ID         postgres.ColumnInteger
	Site       postgres.ColumnString
	Service    postgres.ColumnString
	Postfix    postgres.ColumnString
	ObservedAt postgres.ColumnTimestampz
	State      postgres.ColumnString
	Source     postgres.ColumnString
	CommitSha  postgres.ColumnString
	SchemaCode postgres.ColumnString
	SchemaDb   postgres.ColumnString
	Pending    postgres.ColumnString
	Unknown    postgres.ColumnString
	Error      postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type SiteVersionsTable struct {
	siteVersionsTable

	EXCLUDED siteVersionsTable
}

// AS creates new SiteVersionsTable with assigned alias
func (a SiteVersionsTable) AS(alias string) *SiteVersionsTable {
	return newSiteVersionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SiteVersionsTable with assigned schema name
func (a SiteVersionsTable) FromSchema(schemaName string) *SiteVersionsTable {
	return newSiteVersionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SiteVersionsTable with assigned table prefix
func (a SiteVersionsTable) WithPrefix(prefix string) *SiteVersionsTable {
	return newSiteVersionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SiteVersionsTable with assigned table suffix
func (a SiteVersionsTable) WithSuffix(suffix string) *SiteVersionsTable {
	return newSiteVersionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSiteVersionsTable(schemaName, tableName, alias string) *SiteVersionsTable {
	return &SiteVersionsTable{
		siteVersionsTable: newSiteVersionsTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newSiteVersionsTableImpl("", "excluded", ""),
	}
}

func newSiteVersionsTableImpl(schemaName, tableName, alias string) siteVersionsTable {
	var (
		IDColumn         = postgres.IntegerColumn("id")
		SiteColumn       = postgres.StringColumn("site")
		ServiceColumn    = postgres.StringColumn("service")
		PostfixColumn    = postgres.StringColumn("postfix")
		ObservedAtColumn = postgres.TimestampzColumn("observed_at")
		StateColumn      = postgres.StringColumn("state")
		SourceColumn     = postgres.StringColumn("source")
		CommitShaColumn  = postgres.StringColumn("commit_sha")
		SchemaCodeColumn = postgres.StringColumn("schema_code")
		SchemaDbColumn   = postgres.StringColumn("schema_db")
		PendingColumn    = postgres.StringColumn("pending")
		UnknownColumn    = postgres.StringColumn("unknown")
		ErrorColumn      = postgres.StringColumn("error")
		allColumns       = postgres.ColumnList{IDColumn, SiteColumn, ServiceColumn, PostfixColumn, ObservedAtColumn, StateColumn, SourceColumn, CommitShaColumn, SchemaCodeColumn, SchemaDbColumn, PendingColumn, UnknownColumn, ErrorColumn}
		mutableColumns   = postgres.ColumnList{SiteColumn, ServiceColumn, PostfixColumn, ObservedAtColumn, StateColumn, SourceColumn, CommitShaColumn, SchemaCodeColumn, SchemaDbColumn, PendingColumn, UnknownColumn, ErrorColumn}
		defaultColumns   = postgres.ColumnList{IDColumn, PostfixColumn, ObservedAtColumn, SourceColumn, CommitShaColumn, SchemaCodeColumn, SchemaDbColumn, PendingColumn, UnknownColumn, ErrorColumn}
	)

	return siteVersionsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		Site:       SiteColumn,
		Service:    ServiceColumn,
		Postfix:    PostfixColumn,
		ObservedAt: ObservedAtColumn,
		State:      StateColumn,
		Source:     SourceColumn,
		CommitSha:  CommitShaColumn,
		SchemaCode: SchemaCodeColumn,
		SchemaDb:   SchemaDbColumn,
		Pending:    PendingColumn,
		Unknown:    UnknownColumn,
		Error:      ErrorColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
