//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Deploys = newDeploysTable("public", "deploys", "")

type deploysTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnInteger
	CreatedAt postgres.ColumnTimestampz
	CreatedBy postgres.ColumnString
	Branch    postgres.ColumnString
	Sha       postgres.ColumnString
	Pinned    postgres.ColumnBool

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type DeploysTable struct {
	deploysTable

	EXCLUDED deploysTable
}

// AS creates new DeploysTable with assigned alias
func (a DeploysTable) AS(alias string) *DeploysTable {
	return newDeploysTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new DeploysTable with assigned schema name
func (a DeploysTable) FromSchema(schemaName string) *DeploysTable {
	return newDeploysTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new DeploysTable with assigned table prefix
func (a DeploysTable) WithPrefix(prefix string) *DeploysTable {
	return newDeploysTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new DeploysTable with assigned table suffix
func (a DeploysTable) WithSuffix(suffix string) *DeploysTable {
	return newDeploysTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newDeploysTable(schemaName, tableName, alias string) *DeploysTable {
	return &DeploysTable{
		deploysTable: newDeploysTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newDeploysTableImpl("", "excluded", ""),
	}
}

func newDeploysTableImpl(schemaName, tableName, alias string) deploysTable {
	var (
		IDColumn        = postgres.IntegerColumn("id")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		CreatedByColumn = postgres.StringColumn("created_by")
		BranchColumn    = postgres.StringColumn("branch")
		ShaColumn       = postgres.StringColumn("sha")
		PinnedColumn    = postgres.BoolColumn("pinned")
		allColumns      = postgres.ColumnList{IDColumn, CreatedAtColumn, CreatedByColumn, BranchColumn, ShaColumn, PinnedColumn}
		mutableColumns  = postgres.ColumnList{CreatedAtColumn, CreatedByColumn, BranchColumn, ShaColumn, PinnedColumn}
		defaultColumns  = postgres.ColumnList{IDColumn, CreatedAtColumn, PinnedColumn}
	)

	return deploysTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		CreatedAt: CreatedAtColumn,
		CreatedBy: CreatedByColumn,
		Branch:    BranchColumn,
		Sha:       ShaColumn,
		Pinned:    PinnedColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
