//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Sessions = newSessionsTable("public", "sessions", "")

type sessionsTable struct {
	postgres.Table

	// Columns
	ID             postgres.ColumnString
	UserID         postgres.ColumnInteger
	Username       postgres.ColumnString
	Name           postgres.ColumnString
	AvatarURL      postgres.ColumnString
	AccessLevel    postgres.ColumnInteger
	AccessToken    postgres.ColumnString
	RefreshToken   postgres.ColumnString
	TokenExpiresAt postgres.ColumnTimestampz
	CreatedAt      postgres.ColumnTimestampz
	ExpiresAt      postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type SessionsTable struct {
	sessionsTable

	EXCLUDED sessionsTable
}

// AS creates new SessionsTable with assigned alias
func (a SessionsTable) AS(alias string) *SessionsTable {
	return newSessionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SessionsTable with assigned schema name
func (a SessionsTable) FromSchema(schemaName string) *SessionsTable {
	return newSessionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SessionsTable with assigned table prefix
func (a SessionsTable) WithPrefix(prefix string) *SessionsTable {
	return newSessionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SessionsTable with assigned table suffix
func (a SessionsTable) WithSuffix(suffix string) *SessionsTable {
	return newSessionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSessionsTable(schemaName, tableName, alias string) *SessionsTable {
	return &SessionsTable{
		sessionsTable: newSessionsTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newSessionsTableImpl("", "excluded", ""),
	}
}

func newSessionsTableImpl(schemaName, tableName, alias string) sessionsTable {
	var (
		IDColumn             = postgres.StringColumn("id")
		UserIDColumn         = postgres.IntegerColumn("user_id")
		UsernameColumn       = postgres.StringColumn("username")
		NameColumn           = postgres.StringColumn("name")
		AvatarURLColumn      = postgres.StringColumn("avatar_url")
		AccessLevelColumn    = postgres.IntegerColumn("access_level")
		AccessTokenColumn    = postgres.StringColumn("access_token")
		RefreshTokenColumn   = postgres.StringColumn("refresh_token")
		TokenExpiresAtColumn = postgres.TimestampzColumn("token_expires_at")
		CreatedAtColumn      = postgres.TimestampzColumn("created_at")
		ExpiresAtColumn      = postgres.TimestampzColumn("expires_at")
		allColumns           = postgres.ColumnList{IDColumn, UserIDColumn, UsernameColumn, NameColumn, AvatarURLColumn, AccessLevelColumn, AccessTokenColumn, RefreshTokenColumn, TokenExpiresAtColumn, CreatedAtColumn, ExpiresAtColumn}
		mutableColumns       = postgres.ColumnList{UserIDColumn, UsernameColumn, NameColumn, AvatarURLColumn, AccessLevelColumn, AccessTokenColumn, RefreshTokenColumn, TokenExpiresAtColumn, CreatedAtColumn, ExpiresAtColumn}
		defaultColumns       = postgres.ColumnList{NameColumn, AvatarURLColumn, AccessTokenColumn, RefreshTokenColumn, TokenExpiresAtColumn, CreatedAtColumn}
	)

	return sessionsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		UserID:         UserIDColumn,
		Username:       UsernameColumn,
		Name:           NameColumn,
		AvatarURL:      AvatarURLColumn,
		AccessLevel:    AccessLevelColumn,
		AccessToken:    AccessTokenColumn,
		RefreshToken:   RefreshTokenColumn,
		TokenExpiresAt: TokenExpiresAtColumn,
		CreatedAt:      CreatedAtColumn,
		ExpiresAt:      ExpiresAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
