//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Settings = newSettingsTable("public", "settings", "")

type settingsTable struct {
	postgres.Table

	// Columns
	ID                     postgres.ColumnBool
	GitlabURL              postgres.ColumnString
	GitlabProject          postgres.ColumnString
	GitlabBranch           postgres.ColumnString
	EnvironmentTemplate    postgres.ColumnString
	APIEnvironmentTemplate postgres.ColumnString
	PipelineInputs         postgres.ColumnString
	TriggerAs              postgres.ColumnString
	VersionToken           postgres.ColumnString
	PollSeconds            postgres.ColumnInteger
	AdminUser              postgres.ColumnString
	AdminPasswordHash      postgres.ColumnString
	OAuthClientID          postgres.ColumnString
	OAuthClientSecret      postgres.ColumnString
	UpdatedAt              postgres.ColumnTimestampz
	UpdatedBy              postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type SettingsTable struct {
	settingsTable

	EXCLUDED settingsTable
}

// AS creates new SettingsTable with assigned alias
func (a SettingsTable) AS(alias string) *SettingsTable {
	return newSettingsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SettingsTable with assigned schema name
func (a SettingsTable) FromSchema(schemaName string) *SettingsTable {
	return newSettingsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SettingsTable with assigned table prefix
func (a SettingsTable) WithPrefix(prefix string) *SettingsTable {
	return newSettingsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SettingsTable with assigned table suffix
func (a SettingsTable) WithSuffix(suffix string) *SettingsTable {
	return newSettingsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSettingsTable(schemaName, tableName, alias string) *SettingsTable {
	return &SettingsTable{
		settingsTable: newSettingsTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newSettingsTableImpl("", "excluded", ""),
	}
}

func newSettingsTableImpl(schemaName, tableName, alias string) settingsTable {
	var (
		IDColumn                     = postgres.BoolColumn("id")
		GitlabURLColumn              = postgres.StringColumn("gitlab_url")
		GitlabProjectColumn          = postgres.StringColumn("gitlab_project")
		GitlabBranchColumn           = postgres.StringColumn("gitlab_branch")
		EnvironmentTemplateColumn    = postgres.StringColumn("environment_template")
		APIEnvironmentTemplateColumn = postgres.StringColumn("api_environment_template")
		PipelineInputsColumn         = postgres.StringColumn("pipeline_inputs")
		TriggerAsColumn              = postgres.StringColumn("trigger_as")
		VersionTokenColumn           = postgres.StringColumn("version_token")
		PollSecondsColumn            = postgres.IntegerColumn("poll_seconds")
		AdminUserColumn              = postgres.StringColumn("admin_user")
		AdminPasswordHashColumn      = postgres.StringColumn("admin_password_hash")
		OAuthClientIDColumn          = postgres.StringColumn("oauth_client_id")
		OAuthClientSecretColumn      = postgres.StringColumn("oauth_client_secret")
		UpdatedAtColumn              = postgres.TimestampzColumn("updated_at")
		UpdatedByColumn              = postgres.StringColumn("updated_by")
		allColumns                   = postgres.ColumnList{IDColumn, GitlabURLColumn, GitlabProjectColumn, GitlabBranchColumn, EnvironmentTemplateColumn, APIEnvironmentTemplateColumn, PipelineInputsColumn, TriggerAsColumn, VersionTokenColumn, PollSecondsColumn, AdminUserColumn, AdminPasswordHashColumn, OAuthClientIDColumn, OAuthClientSecretColumn, UpdatedAtColumn, UpdatedByColumn}
		mutableColumns               = postgres.ColumnList{GitlabURLColumn, GitlabProjectColumn, GitlabBranchColumn, EnvironmentTemplateColumn, APIEnvironmentTemplateColumn, PipelineInputsColumn, TriggerAsColumn, VersionTokenColumn, PollSecondsColumn, AdminUserColumn, AdminPasswordHashColumn, OAuthClientIDColumn, OAuthClientSecretColumn, UpdatedAtColumn, UpdatedByColumn}
		defaultColumns               = postgres.ColumnList{IDColumn, GitlabURLColumn, GitlabProjectColumn, GitlabBranchColumn, EnvironmentTemplateColumn, APIEnvironmentTemplateColumn, PipelineInputsColumn, TriggerAsColumn, VersionTokenColumn, PollSecondsColumn, AdminUserColumn, AdminPasswordHashColumn, OAuthClientIDColumn, OAuthClientSecretColumn, UpdatedAtColumn, UpdatedByColumn}
	)

	return settingsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                     IDColumn,
		GitlabURL:              GitlabURLColumn,
		GitlabProject:          GitlabProjectColumn,
		GitlabBranch:           GitlabBranchColumn,
		EnvironmentTemplate:    EnvironmentTemplateColumn,
		APIEnvironmentTemplate: APIEnvironmentTemplateColumn,
		PipelineInputs:         PipelineInputsColumn,
		TriggerAs:              TriggerAsColumn,
		VersionToken:           VersionTokenColumn,
		PollSeconds:            PollSecondsColumn,
		AdminUser:              AdminUserColumn,
		AdminPasswordHash:      AdminPasswordHashColumn,
		OAuthClientID:          OAuthClientIDColumn,
		OAuthClientSecret:      OAuthClientSecretColumn,
		UpdatedAt:              UpdatedAtColumn,
		UpdatedBy:              UpdatedByColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
