//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Sites = newSitesTable("public", "sites", "")

type sitesTable struct {
	postgres.Table

	// Columns
	Name       postgres.ColumnString
	VersionURL postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type SitesTable struct {
	sitesTable

	EXCLUDED sitesTable
}

// AS creates new SitesTable with assigned alias
func (a SitesTable) AS(alias string) *SitesTable {
	return newSitesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SitesTable with assigned schema name
func (a SitesTable) FromSchema(schemaName string) *SitesTable {
	return newSitesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SitesTable with assigned table prefix
func (a SitesTable) WithPrefix(prefix string) *SitesTable {
	return newSitesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SitesTable with assigned table suffix
func (a SitesTable) WithSuffix(suffix string) *SitesTable {
	return newSitesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSitesTable(schemaName, tableName, alias string) *SitesTable {
	return &SitesTable{
		sitesTable: newSitesTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newSitesTableImpl("", "excluded", ""),
	}
}

func newSitesTableImpl(schemaName, tableName, alias string) sitesTable {
	var (
		NameColumn       = postgres.StringColumn("name")
		VersionURLColumn = postgres.StringColumn("version_url")
		allColumns       = postgres.ColumnList{NameColumn, VersionURLColumn}
		mutableColumns   = postgres.ColumnList{VersionURLColumn}
		defaultColumns   = postgres.ColumnList{VersionURLColumn}
	)

	return sitesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Name:       NameColumn,
		VersionURL: VersionURLColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
