//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Services struct {
	Name    string `sql:"primary_key"`
	Postfix string `sql:"primary_key"`
	Kind    string
	Sites   string
}
