//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type DeployRuns struct {
	ID         int64 `sql:"primary_key"`
	DeployID   int64
	Site       string
	PipelineID *int64
	WebURL     string
	Status     string
	Error      string
	UpdatedAt  time.Time
}
