//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Sessions struct {
	ID             string `sql:"primary_key"`
	UserID         int64
	Username       string
	Name           string
	AvatarURL      string
	AccessLevel    int32
	AccessToken    string
	RefreshToken   string
	TokenExpiresAt time.Time
	CreatedAt      time.Time
	ExpiresAt      time.Time
}
