//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Settings struct {
	ID                bool `sql:"primary_key"`
	GitlabURL         string
	GitlabProject     string
	GitlabBranch      string
	VersionToken      string
	PollSeconds       int32
	AdminUser         string
	AdminPasswordHash string
	UpdatedAt         time.Time
	UpdatedBy         string
	OAuthClientID     string
	OAuthClientSecret string
}
