//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type SiteVersions struct {
	ID         int64 `sql:"primary_key"`
	Site       string
	ObservedAt time.Time
	State      string
	CommitSha  string
	SchemaCode string
	SchemaDb   string
	Pending    string
	Unknown    string
	Error      string
}
